/**
 * Pruned document library: latest annual report, results, and sustainability report.
 * (c) Pernod Ricard. Generated by scripts/pdf-crawl.mjs + prune-pdfs.mjs.
 */
export interface DocItem { title: string; file: string; section: string; kb: number }
export const DOCUMENTS: DocItem[] = [
  {
    "title": "FY25 Universal Registration Document",
    "file": "/documents/fy25-universal-registration-document-vuk.pdf",
    "section": "annual",
    "kb": 13066
  },
  {
    "title": "Check out our FY25 Annual Report",
    "file": "/documents/pernod_ricard_iar25_english.pdf",
    "section": "investors",
    "kb": 16489
  },
  {
    "title": "Download file",
    "file": "/documents/press-release-9m-fy26.pdf",
    "section": "investors",
    "kb": 538
  },
  {
    "title": "Presentation",
    "file": "/documents/sales-and-results-fy25.pdf",
    "section": "investors",
    "kb": 6159
  },
  {
    "title": "Presentation",
    "file": "/documents/pernod-ricard-fy24-full-year-comfi-final_1.pdf",
    "section": "investors",
    "kb": 7974
  },
  {
    "title": "Presentation (pdf)",
    "file": "/documents/sales-and-results-fy24-h1_4.pdf",
    "section": "investors",
    "kb": 4183
  },
  {
    "title": "Presentation (pdf)",
    "file": "/documents/fy23-q1-sales.pdf",
    "section": "investors",
    "kb": 2031
  },
  {
    "title": "Presentation (pdf)",
    "file": "/documents/burex-full-en-vtg.7stream.pdf",
    "section": "investors",
    "kb": 13940
  },
  {
    "title": "Presentation (pdf)",
    "file": "/documents/sales-and-results-h1-fy23_5.pdf",
    "section": "investors",
    "kb": 12037
  },
  {
    "title": "Presentation (pdf)",
    "file": "/documents/sales-and-results-9m-fy23.pdf",
    "section": "investors",
    "kb": 3330
  },
  {
    "title": "Presentation (pdf)",
    "file": "/documents/sales-and-results-fy23.pdf",
    "section": "investors",
    "kb": 5665
  },
  {
    "title": "Press release",
    "file": "/documents/agm-press-release-27-october-2025.pdf",
    "section": "investors",
    "kb": 1663
  },
  {
    "title": "Press release",
    "file": "/documents/press-release-fy24-h1.pdf",
    "section": "investors",
    "kb": 697
  },
  {
    "title": "Press release",
    "file": "/documents/press-release-q3-fy24.pdf",
    "section": "investors",
    "kb": 394
  },
  {
    "title": "Transcript (pdf)",
    "file": "/documents/pernod-ricard-h1-fy24-analyst-call-transcript.pdf",
    "section": "investors",
    "kb": 102
  },
  {
    "title": "Transcript (pdf)",
    "file": "/documents/final-transcript-fy24-9m_0.pdf",
    "section": "investors",
    "kb": 2586
  },
  {
    "title": "Transcript (pdf)",
    "file": "/documents/pernod-ricard-fy24-results-transcript.pdf",
    "section": "investors",
    "kb": 275
  },
  {
    "title": "Presentation",
    "file": "/documents/sales-and-results-fy25-h1_0.pdf",
    "section": "results",
    "kb": 5684
  },
  {
    "title": "View the presentation",
    "file": "/documents/pernod-ricard-fy26-h1-financial-communication.pdf",
    "section": "results",
    "kb": 9257
  },
  {
    "title": "Auditors' report - Review of sustainability FY25",
    "file": "/documents/auditors-report-review-of-sustainability-fy25.pdf",
    "section": "sustainability",
    "kb": 107
  }
];
