/**
 * Structured content extracted from key Pernod Ricard corporate pages.
 * Headings/lead copy + imagery for a design comp; © Pernod Ricard.
 * Generated by scripts/pages-crawl.mjs.
 */
export type Block =
  | { t: "h"; level: number; v: string }
  | { t: "p"; v: string }
  | { t: "img"; v: string; alt: string };

export interface PageContent {
  key: string;
  url: string;
  title: string;
  description: string;
  hero: string | null;
  stats: { value: string; label: string }[];
  blocks: Block[];
}

export const PAGES: Record<string, PageContent> = {
  "group": {
    "key": "group",
    "url": "https://www.pernod-ricard.com/en/our-group",
    "title": "Our Group",
    "description": "Pernod Ricard has the most comprehensive portfolio in the industry, with over 200 spirits and champagnes brands distributed in 160 countries. The…",
    "hero": null,
    "stats": [],
    "blocks": [
      {
        "t": "h",
        "level": 1,
        "v": "Who we are"
      },
      {
        "t": "p",
        "v": "Pernod Ricard has the most comprehensive portfolio in the industry, with over 200 spirits and champagnes brands distributed in 160 countries. The Group puts its expertise at the service of authentic moments of sharing, while acting ethically and responsibly to have a positive imp"
      },
      {
        "t": "h",
        "level": 2,
        "v": "Our purpose"
      },
      {
        "t": "p",
        "v": "Our products embody the excellence of our know-how and our passion for brand building. Our champagnes and spirits tell genuine stories, bringing unique sensory experiences to life during unforgettable moments."
      },
      {
        "t": "p",
        "v": "We act for the responsible consumption of our brands, standing firm in the belief that there is no conviviality in excess."
      },
      {
        "t": "img",
        "v": "/images/pages/group/00-alexandre_ricard_portrait_1440-1080.jpg",
        "alt": "Alexandre Ricard"
      },
      {
        "t": "p",
        "v": "• Our Board of Directors, its Committees, and the Executive Committee ensure that we lead our organisation in an ethical and transparent manner and in the best interests of our stakeholders."
      },
      {
        "t": "img",
        "v": "/images/pages/group/01-_paul_ricard_and_jean_hemard_.jpg",
        "alt": "Paul Ricard and Jean Hemard sign a contract at the creation of Pernod Ricard in 1975."
      },
      {
        "t": "p",
        "v": "In 1975 Paul Ricard and Jean Hémard founded Pernod Ricard by merging their two anise-based spirits companies. The two partners set out with shared enthusiasm, creative innovation and an ambitious goal of global leadership."
      },
      {
        "t": "img",
        "v": "/images/pages/group/02-originalsizejpeg-bbh-still011.jpg",
        "alt": "Friends celebrate a toast while having a meal seated at a table in a garden."
      },
      {
        "t": "p",
        "v": "As an industry leader we are mindful of our influence and so embedded in our business is respect and responsibility for each other, our communities and our planet because we believe there is no conviviality in excess, especially when it comes to drinking."
      },
      {
        "t": "img",
        "v": "/images/pages/group/03-sanja-marusic_carte-blanche.jpg",
        "alt": "A photograph from Sanja Marušić's series Naturally Committed."
      },
      {
        "t": "h",
        "level": 2,
        "v": "Our Artistic Legacy"
      },
      {
        "t": "p",
        "v": "Our founder Paul Ricard’s love of creativity and art drove his philanthropy, and we carry on that mission today by supporting artists and artistic creation."
      },
      {
        "t": "h",
        "level": 2,
        "v": "Related pages"
      },
      {
        "t": "img",
        "v": "/images/pages/group/04-hp_0002_brand-home_3.jpg",
        "alt": "Jameson Distillery Bow St. in Dublin, Ireland"
      },
      {
        "t": "img",
        "v": "/images/pages/group/05-pernod-20ricard-20hq.jpg",
        "alt": "Interior view of The Island, Pernod Ricard's headquarters in Paris, France."
      }
    ]
  },
  "group-role-society": {
    "key": "group-role-society",
    "url": "https://www.pernod-ricard.com/en/our-group/our-role-society",
    "title": "Our Role in Society",
    "description": "Embedded into our business is respect and responsibility for each other, our communities, and our planet because we believe there is no conviviality…",
    "hero": null,
    "stats": [],
    "blocks": [
      {
        "t": "img",
        "v": "/images/pages/group-role-society/00-originalsizejpeg-bbh-still011.jpg",
        "alt": "Friends celebrate a toast while having a meal seated at a table in a garden."
      },
      {
        "t": "h",
        "level": 1,
        "v": "Our Role in Society"
      },
      {
        "t": "p",
        "v": "Embedded into our business is respect and responsibility for each other, our communities, and our planet because we believe there is no conviviality in excess, especially when it comes to drinking."
      },
      {
        "t": "h",
        "level": 2,
        "v": "Creating a More Convivial World, a World Without Excess"
      },
      {
        "t": "p",
        "v": "We are passionate hosts... a global family of exceptional people who are committed to fighting alcohol misuse and creating a better way to live and work together, to bring Good Times from a Good Place, today and for generations to come."
      },
      {
        "t": "p",
        "v": "Reducing harmful drinking is core to our corporate premiumisation strategy. We want to ensure that our brands are enjoyed in moderation and responsibly and we encourage our employees and consumers to be responsible hosts and respectful guests."
      },
      {
        "t": "p",
        "v": "We actively participate in the global public debate around alcohol and health. We respect our consumers and set high standards for marketing and self-regulation and operate with transparency about all our policies."
      },
      {
        "t": "p",
        "v": "In the markets where we distribute our products, Pernod Ricard contributes to alcohol harm reduction through targeted interventions. In 2022, 93% of markets have contributed to a local or global responsible drinking initiative."
      },
      {
        "t": "p",
        "v": "We are a founding member of the International Alliance for Responsible Drinking (IARD), established in 2015, as well as its predecessor organisations, ICAP and GAP-G. IARD is a not-for-profit organisation dedicated to reducing harmful drinking and promoting understanding of respo"
      },
      {
        "t": "p",
        "v": "We play a leading role within industry trade associations and contribute to relevant conversations related to public policy, in a transparent and ethical way."
      },
      {
        "t": "p",
        "v": "Pernod Ricard is committed to upholding these principles by continually engaging with our own workforce and working with relevant stakeholders such as government bodies, educators, and associations to address issues and improve our societies for everyone."
      },
      {
        "t": "p",
        "v": "Code for Commercial CommunicationsCode of Business ConductGlobal Human Rights Policy"
      },
      {
        "t": "img",
        "v": "/images/pages/group-role-society/01-laurent-scheer_0533-28c-29-antoine-doyen.jpg",
        "alt": "Laurent Scheer"
      },
      {
        "t": "p",
        "v": "\"Pernod Ricard’s ambition is to be a responsible and committed stakeholder in society. This ambition translates into an ambitious Sustainability & Responsibility strategy, as well as a contribution to civil society dialogue on matters that are relevant to the company."
      },
      {
        "t": "p",
        "v": "Our public affairs teams around the world are tasked with this contribution: sharing our views, informing policy makers about our industry, suggesting positive solutions."
      },
      {
        "t": "p",
        "v": "We seek to contribute thoughts and ideas, alongside all other stakeholders, to various discussions, such as: what is a fair and effective tax policy, how can responsible drinking be encouraged, how to regulate international trade or how to secure the highest levels of food safety"
      },
      {
        "t": "p",
        "v": "Laurent Scheer, VP, Global Public Affairs & Alcohol in Society"
      },
      {
        "t": "h",
        "level": 2,
        "v": "Alcohol and health"
      },
      {
        "t": "p",
        "v": "Our “raison d’être” is to create moments of conviviality. We believe that, when consumed responsibly, our products can contribute to enjoyment and pleasure, and bring people together. Conviviality is by essence a question of individual and collective responsibility. On the other "
      },
      {
        "t": "p",
        "v": "We believe that, as an alcohol beverage producer, Pernod Ricard has a role to play in the reduction of irresponsible use of alcohol. We actively participate in the global public debate around responsible drinking through the International Alliance of Responsible Drinking (IARD), "
      },
      {
        "t": "p",
        "v": "Drinking alcohol is not for everyone and may be inappropriate under some circumstances. Underage individuals, pregnant women and others advised not to drink by their health care practitioners should not drink alcohol. People who are driving should strictly comply with the blood a"
      },
      {
        "t": "p",
        "v": "We respect the right of every adult to choose whether to consume alcoholic beverages or not, and we encourage those who decide to drink to do so responsibly and to follow the official drinking guidelines and recommendations on alcohol consumption applicable in their local country"
      },
      {
        "t": "p",
        "v": "We acknowledge that drinking alcohol may cause health problems in certain circumstances, in particular regular heavy drinking which has been associated with a number of illnesses, including certain types of cancer."
      },
      {
        "t": "p",
        "v": "Excessive drinking, and in particular binge drinking, can cause injury, social issues, and can be harmful to health; as a consequence it has no place in the responsible enjoyment to our products."
      },
      {
        "t": "p",
        "v": "To learn more about WHO data on trends in consumption, drinking patterns and harm in different regions of the world To learn more about Pernod Ricard’s position on alcohol and health To learn more about Pernod Ricard’s actions on responsible drinking"
      },
      {
        "t": "img",
        "v": "/images/pages/group-role-society/02-marketing-self-regulation.jpg",
        "alt": ""
      }
    ]
  },
  "group-history": {
    "key": "group-history",
    "url": "https://www.pernod-ricard.com/en/our-group/our-history",
    "title": "Our History",
    "description": "From our birth in Marseille to a worldwide story of growth, success and transformation",
    "hero": null,
    "stats": [
      {
        "value": "1",
        "label": "slide of 4"
      },
      {
        "value": "1",
        "label": "slide of 5"
      },
      {
        "value": "2020",
        "label": ": Significant investment in Ki No Bi Jap"
      }
    ],
    "blocks": [
      {
        "t": "img",
        "v": "/images/pages/group-history/00-img_2459m2.jpg",
        "alt": "Pernod Ricard - header"
      },
      {
        "t": "h",
        "level": 1,
        "v": "Our History"
      },
      {
        "t": "p",
        "v": "From our birth in Marseille to a worldwide story of growth, success and transformation"
      },
      {
        "t": "h",
        "level": 2,
        "v": "Our roots"
      },
      {
        "t": "p",
        "v": "We trace our roots all the way back to 1805, when Pernod was born. 1932 saw the creation of Ricard - and the two families joined forces in 1975."
      },
      {
        "t": "p",
        "v": "Today, Pernod Ricard is present in over 160 countries. Its global reach is testimony to 50 years of growth, and to its transformation into a responsible and sustainable company fit for the future."
      },
      {
        "t": "h",
        "level": 2,
        "v": "1970s – 1990s"
      },
      {
        "t": "img",
        "v": "/images/pages/group-history/01-_paul_ricard_and_jean_hemard_.jpg",
        "alt": "Paul Ricard and Jean Hemard sign a contract at the creation of Pernod Ricard in 1975."
      },
      {
        "t": "p",
        "v": "The merger of Pernod and Ricard brings together two French anise-based spirits."
      },
      {
        "t": "img",
        "v": "/images/pages/group-history/02-originalsizejpeg-jameson_bb_act_1_docume.jpg",
        "alt": "Jameson"
      },
      {
        "t": "p",
        "v": "Acquisition of leading Irish whiskey producer Irish Distillers, owner of Jameson."
      },
      {
        "t": "img",
        "v": "/images/pages/group-history/03-brand-george-wyndham-shiraz-grenache-lif.jpg",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/group-history/04-brand-havana-club-7-lifestyle-original.jpg",
        "alt": "brand-havana-club-7-lifestyle-original"
      },
      {
        "t": "p",
        "v": "Creation of joint venture between Pernod Ricard and the Cuban rum company, Cuba Ron, to market and sell Havana Club."
      },
      {
        "t": "img",
        "v": "/images/pages/group-history/05-originalsizejpeg-absolut_eoy22_fizzy_sod.jpg",
        "alt": "Absolut"
      },
      {
        "t": "h",
        "level": 2,
        "v": "2000s"
      },
      {
        "t": "h",
        "level": 2,
        "v": "2010s"
      },
      {
        "t": "img",
        "v": "/images/pages/group-history/06-responsiball_day_2019_waw_7.jpg",
        "alt": ""
      },
      {
        "t": "p",
        "v": "Launch of Responsib’All Day, Pernod Ricard’s annual social engagement volunteer event for the group’s entire workforce."
      },
      {
        "t": "img",
        "v": "/images/pages/group-history/07-brand-monkey47-sloe-gin-lifestyle-origin.jpg",
        "alt": ""
      }
    ]
  },
  "sustainability": {
    "key": "sustainability",
    "url": "https://www.pernod-ricard.com/en/sustainability-responsibility",
    "title": "Sustainability & Responsibility",
    "description": "We believe that there can be no convivialité with excess and strive to be sustainable and responsible at every step, from grain to glass.",
    "hero": null,
    "stats": [
      {
        "value": "1",
        "label": "slide of 4"
      }
    ],
    "blocks": [
      {
        "t": "img",
        "v": "/images/pages/sustainability/00-previewlarge-kilmalid_-_clyde_hall_03.jpg",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/sustainability/01-wlg-full-061.jpg",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/sustainability/02-7-1.png",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/sustainability/00-previewlarge-kilmalid_-_clyde_hall_03.jpg",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/sustainability/01-wlg-full-061.jpg",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/sustainability/02-7-1.png",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/sustainability/00-previewlarge-kilmalid_-_clyde_hall_03.jpg",
        "alt": ""
      },
      {
        "t": "h",
        "level": 1,
        "v": "Sustainability & Responsibility"
      },
      {
        "t": "p",
        "v": "We believe that there can be no convivialité with excess and strive to be sustainable and responsible at every step, from grain to glass."
      },
      {
        "t": "img",
        "v": "/images/pages/sustainability/03-framework-simplified_framework-sdgs.png",
        "alt": ""
      },
      {
        "t": "h",
        "level": 2,
        "v": "Our Roadmap to 2030"
      },
      {
        "t": "p",
        "v": "Our Sustainability & Responsibility roadmap directly supports the United Nations Sustainable Development Goals (SDGs) and is aligned to their 2030 plan."
      },
      {
        "t": "p",
        "v": "The four pillars of our roadmap, Nurturing Terroir, Valuing People, Circular Making and Responsible Hosting, address all aspects of our business from grain to glass. Each of our pillars sets out ambitious goals and targets to drive innovation, brand differentiation and employee a"
      },
      {
        "t": "h",
        "level": 2,
        "v": "Good Times from a Good Place"
      },
      {
        "t": "p",
        "v": "We are Créateurs de Convivialité. True to our founding spirit, we’ve been bringing people together, inviting them to share authentic experiences and making new friends every day through our world-class portfolio of premium champagnes and spirits."
      },
      {
        "t": "p",
        "v": "We are passionate hosts - a family of exceptional people who are committing to promoting responsible drinking and creating a better way to live and work together to bring good times today and for generations to come."
      },
      {
        "t": "p",
        "v": "We are respectful guests who care for and strive to protect and nurture the terroirs and environments we live in. We partner with local farmers and respect local communities to benefit our planet, our consumers and our business."
      },
      {
        "t": "p",
        "v": "We bring Good Times from a Good Place, to create a more convivial world, a world without excess."
      },
      {
        "t": "h",
        "level": 2,
        "v": "Focus on"
      },
      {
        "t": "img",
        "v": "/images/pages/sustainability/04-5c0e2aaa-1baa-412a-8e58-ab5777fbfb22_0.jpg",
        "alt": ""
      },
      {
        "t": "h",
        "level": 3,
        "v": "Nurturing Terroir"
      },
      {
        "t": "p",
        "v": "Our products take their character from the land where they were grown. We nurture every terroir and its biodiversity and respond to the challenges of climate change to ensure quality ingredients now and for generations to come."
      },
      {
        "t": "img",
        "v": "/images/pages/sustainability/05-responsiballday2024-266_hd.jpg",
        "alt": ""
      },
      {
        "t": "h",
        "level": 3,
        "v": "Valuing People"
      },
      {
        "t": "p",
        "v": "We provide equal opportunities and foster a respectful, fair and safe work environment where everyone can be their true selves and thrive, within our company and beyond."
      },
      {
        "t": "img",
        "v": "/images/pages/sustainability/06-old_midleton_distillery.jpg",
        "alt": ""
      }
    ]
  },
  "investors": {
    "key": "investors",
    "url": "https://www.pernod-ricard.com/en/investors",
    "title": "Investors",
    "description": "Pernod Ricard’s investor relations information including key figures, share and debt information, publications, financial calendar, governance and…",
    "hero": null,
    "stats": [
      {
        "value": "4,7%",
        "label": "+0,00%"
      },
      {
        "value": "847",
        "label": "(31)"
      },
      {
        "value": "4%",
        "label": "Net Sales4 9734 635(338)(7)%194"
      }
    ],
    "blocks": [
      {
        "t": "img",
        "v": "/images/pages/investors/00-pernod-20ricard-20hq.jpg",
        "alt": "Interior view of The Island, Pernod Ricard's headquarters in Paris, France."
      },
      {
        "t": "h",
        "level": 1,
        "v": "Investors"
      },
      {
        "t": "p",
        "v": "Pernod Ricard’s investor relations information including key figures, share and debt information, publications, financial calendar, governance and more."
      },
      {
        "t": "p",
        "v": "Pernod Ricard is the No.2 worldwide producer of champagnes and spirits. The Group, which owns 17 of the Top 100 Spirits Brands, holds one of the most prestigious and comprehensive portfolios in the industry with over 240 premium brands distributed across more than 160 markets."
      },
      {
        "t": "p",
        "v": "The Group’s mission is to unlock the magic of human connections by bringing “Good Times from a Good Place”, in line with its Sustainability and Responsibility roadmap. Pernod Ricard’s decentralised organisation empowers its 19,480 employees to be on-the-ground ambassadors of its "
      },
      {
        "t": "img",
        "v": "/images/pages/investors/01-previewmedium-codigo_fy26_kap09367.jpg",
        "alt": ""
      },
      {
        "t": "h",
        "level": 2,
        "v": "Pernod Ricard USA Q&A 2026"
      },
      {
        "t": "p",
        "v": "Join Conor McQuaid, CEO of Pernod Ricard North America, for a live Q&A on Pernod Ricard’s US business, video available from 07:30am (Paris time), followed by the live discussion at 15:00 (Paris time) on Thursday 28th May 2026.InvitationAccess the webcastVideoTranscript"
      },
      {
        "t": "img",
        "v": "/images/pages/investors/02-previewmedium-jameson_fy26_photography_o.jpg",
        "alt": ""
      },
      {
        "t": "h",
        "level": 2,
        "v": "FY26 Q3 Sales and Results"
      },
      {
        "t": "p",
        "v": "Pernod Ricard announces their results Thursday 16 April 9am CEST."
      },
      {
        "t": "img",
        "v": "/images/pages/investors/03-previewlarge-chivas_regal_18_e-com_lifes.png",
        "alt": ""
      },
      {
        "t": "h",
        "level": 2,
        "v": "H1 FY26 - Sales and Results"
      },
      {
        "t": "p",
        "v": "Pernod Ricard present its H1 FY26 - Sales and Results on Thursday, February 19, 2026.Watch the webcastRead the press releaseView the presentation"
      },
      {
        "t": "img",
        "v": "/images/pages/investors/04-ag2024-pernodricard_0509_c_stephane_sby_.jpg",
        "alt": ""
      },
      {
        "t": "h",
        "level": 2,
        "v": "Annual General Meeting 2025"
      },
      {
        "t": "p",
        "v": "The Pernod Ricard Annual General Meeting will take place on Monday 27 October, 2pm (Paris time) at Salle Pleyel, 252 Rue du Faubourg Saint-Honoré, 75008 Paris.View the documentationFollow the webcast"
      },
      {
        "t": "img",
        "v": "/images/pages/investors/05-03142023_hugo_lecrux_royal_salute6028-2.jpg",
        "alt": ""
      },
      {
        "t": "h",
        "level": 2,
        "v": "FY26 Q1 Sales and Results"
      },
      {
        "t": "p",
        "v": "Pernod Ricard announces their results Thursday 16 October 9am CEST."
      },
      {
        "t": "h",
        "level": 2,
        "v": "Group Financial Figures"
      },
      {
        "t": "h",
        "level": 3,
        "v": "Consolidated Results FY25"
      },
      {
        "t": "h",
        "level": 3,
        "v": "Americas FY25"
      },
      {
        "t": "h",
        "level": 3,
        "v": "Asia-Rest of the World FY25"
      },
      {
        "t": "h",
        "level": 3,
        "v": "Europe FY25"
      },
      {
        "t": "h",
        "level": 3,
        "v": "Simplified Balance Sheet FY25"
      }
    ]
  },
  "careers": {
    "key": "careers",
    "url": "https://www.pernod-ricard.com/en/careers",
    "title": "Careers",
    "description": "Our premium brands are powered by over 19,000 talented and passionate people across the globe.",
    "hero": null,
    "stats": [],
    "blocks": [
      {
        "t": "img",
        "v": "/images/pages/careers/00-img.webp",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/careers/01-img.webp",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/careers/02-img.webp",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/careers/00-img.webp",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/careers/01-img.webp",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/careers/02-img.webp",
        "alt": ""
      },
      {
        "t": "img",
        "v": "/images/pages/careers/00-img.webp",
        "alt": ""
      },
      {
        "t": "h",
        "level": 1,
        "v": "Create Conviviality with us"
      },
      {
        "t": "p",
        "v": "Our premium brands are powered by over 19,000 talented and passionate people across the globe."
      },
      {
        "t": "h",
        "level": 3,
        "v": "Why join Pernod Ricard?"
      },
      {
        "t": "p",
        "v": "Founded in 1975, our Group is built on a rich legacy and bold ambitions for the future. Pernod Ricard represents over 200 brands like Absolut Vodka, Jameson Whiskey and Martell Cognac."
      },
      {
        "t": "p",
        "v": "Across 60 countries with affiliates, we offer opportunities across a wide range of functions from manufacturing to marketing, sustainability to on-trade, supply chain to digital and more."
      },
      {
        "t": "img",
        "v": "/images/pages/careers/03-img.webp",
        "alt": ""
      },
      {
        "t": "h",
        "level": 2,
        "v": "Where Conviviality is at Work"
      },
      {
        "t": "p",
        "v": "It’s the Pernod Ricard way, and it’s rooted in every one of us who works here. It means feeling empowered to be yourself.It means having a passion for challenge and collectively making great things happen. It means collaboration from across the room or across the globe."
      },
      {
        "t": "h",
        "level": 3,
        "v": "We foster empowering workplaces and offer exciting opportunities that encourage you to grow. What does this look like?"
      },
      {
        "t": "img",
        "v": "/images/pages/careers/04-img.webp",
        "alt": ""
      },
      {
        "t": "p",
        "v": "Conviviality is in our DNA and connects us beyond borders. The more our workforce reflects the richness of consumers and society, the better we can shape the future of our industry."
      },
      {
        "t": "img",
        "v": "/images/pages/careers/05-img.webp",
        "alt": ""
      },
      {
        "t": "p",
        "v": "Being responsible in a safe and sustainable way is at the core of everything Pernod Ricard does. We cherish the land where our products are grown and are committed to bringing Good Times from a Good Place."
      },
      {
        "t": "img",
        "v": "/images/pages/careers/06-img.webp",
        "alt": ""
      },
      {
        "t": "h",
        "level": 2,
        "v": "Craft your path"
      },
      {
        "t": "p",
        "v": "Own your career and craft the path you want to take. Be empowered to do your best and make the most of unique opportunities to learn and grow. Supported by equitable and skills-based processes, throughout your time with us you will continuously develop and learn. On average, empl"
      },
      {
        "t": "img",
        "v": "/images/pages/careers/07-img.webp",
        "alt": ""
      }
    ]
  }
};
