/**
 * Pernod Ricard portfolio, extracted from pernod-ricard.com/en/brands.
 * Brand names + categories are factual. Logos & photography are © Pernod Ricard
 * and its brand owners, used here only for this design comp. See
 * public/images/pernod/NOTICE.md before any public or production use.
 * Generated by scripts/gen-brands.mjs, do not edit by hand.
 */

export interface PortfolioBrand {
  name: string;
  category: string;
  logo: string;
  hero: string | null;
}

export const PORTFOLIO_CATEGORIES = [
  "Scotch Whisky",
  "Irish Whiskey",
  "World Whiskies",
  "Cognac & Brandy",
  "Vodka",
  "Gin",
  "Liqueur & Bitters",
  "Rum",
  "Champagne",
  "Tequila & Mezcal",
  "Aperitif",
  "Wine",
  "Spirits",
] as const;

export const PORTFOLIO: PortfolioBrand[] = [
  {
    "name": "Aberlour",
    "category": "Scotch Whisky",
    "logo": "/images/pernod/49-aberlour_logo_240.png",
    "hero": null
  },
  {
    "name": "Absolut",
    "category": "Vodka",
    "logo": "/images/pernod/35-brand-absolut-logo-240px_1.png",
    "hero": null
  },
  {
    "name": "Absolut Elyx",
    "category": "Vodka",
    "logo": "/images/pernod/65-brand-absolut-elyx-logo-240px.png",
    "hero": null
  },
  {
    "name": "Altos",
    "category": "Tequila & Mezcal",
    "logo": "/images/pernod/50-brand-altos-logo-240px_0.png",
    "hero": null
  },
  {
    "name": "Ararat",
    "category": "Cognac & Brandy",
    "logo": "/images/pernod/86-brand-ararat-logo-240px.png",
    "hero": null
  },
  {
    "name": "Augier",
    "category": "Cognac & Brandy",
    "logo": "/images/pernod/51-brand-augier-logo-blue-240px.png",
    "hero": null
  },
  {
    "name": "Avión",
    "category": "Tequila & Mezcal",
    "logo": "/images/pernod/52-brand-avion-logo-240px.png",
    "hero": null
  },
  {
    "name": "Ballantine's",
    "category": "Scotch Whisky",
    "logo": "/images/pernod/36-ballantines_logo_240.png",
    "hero": null
  },
  {
    "name": "Beefeater",
    "category": "Gin",
    "logo": "/images/pernod/37-beefeater-logo_240.png",
    "hero": "/images/pernod/11-beefeater_kv_958x1048_0.jpg"
  },
  {
    "name": "Belaire",
    "category": "Champagne",
    "logo": "/images/pernod/69-belaire.png",
    "hero": null
  },
  {
    "name": "Bumbu",
    "category": "Rum",
    "logo": "/images/pernod/62-bumbu.png",
    "hero": null
  },
  {
    "name": "Château Sainte Marguerite",
    "category": "Wine",
    "logo": "/images/pernod/63-stmarguerite_newlogo_cmyk_anthracite_prod_250326.png",
    "hero": null
  },
  {
    "name": "Chivas Regal",
    "category": "Scotch Whisky",
    "logo": "/images/pernod/38-chivas_logo_blue_240.png",
    "hero": null
  },
  {
    "name": "Código 1530",
    "category": "Tequila & Mezcal",
    "logo": "/images/pernod/64-codigo_logo_blue.png",
    "hero": null
  },
  {
    "name": "Del Maguey",
    "category": "Tequila & Mezcal",
    "logo": "/images/pernod/53-brand-delmaguey-logo-240px.png",
    "hero": null
  },
  {
    "name": "Havana Club",
    "category": "Rum",
    "logo": "/images/pernod/39-havana_club_logo-resize_blue.png",
    "hero": "/images/pernod/29-havana-club.jpg"
  },
  {
    "name": "Imperial",
    "category": "World Whiskies",
    "logo": "/images/pernod/88-imperial_logo_240.png",
    "hero": null
  },
  {
    "name": "Italicus",
    "category": "Liqueur & Bitters",
    "logo": "/images/pernod/55-brand-italicus-logo-240px_0.png",
    "hero": null
  },
  {
    "name": "J.P. Wiser's",
    "category": "World Whiskies",
    "logo": "/images/pernod/89-brand_jpwiser_logo_blue.png",
    "hero": null
  },
  {
    "name": "Jameson",
    "category": "Irish Whiskey",
    "logo": "/images/pernod/40-brand-jameson-logo-240px.png",
    "hero": "/images/pernod/27-jameson_distillery_bow_st_bar.jpg"
  },
  {
    "name": "Jefferson's",
    "category": "World Whiskies",
    "logo": "/images/pernod/56-jeffersons-bourbon-blue.png",
    "hero": null
  },
  {
    "name": "Kahlúa",
    "category": "Liqueur & Bitters",
    "logo": "/images/pernod/90-kahlua-logo_240.png",
    "hero": null
  },
  {
    "name": "Kenwood",
    "category": "Wine",
    "logo": "/images/pernod/100-brand-kenwood-logo-240px_0.png",
    "hero": null
  },
  {
    "name": "Ki No Bi",
    "category": "Gin",
    "logo": "/images/pernod/82-knb_logo_250.png",
    "hero": null
  },
  {
    "name": "L'Orbe",
    "category": "Vodka",
    "logo": "/images/pernod/66-logo_l-orbe_250-blue.png",
    "hero": null
  },
  {
    "name": "La Hechicera",
    "category": "Rum",
    "logo": "/images/pernod/67-la-20hechicera-202.png",
    "hero": "/images/pernod/30-originalsizejpeg-la_hechicera_finales_web-44_0.jpg"
  },
  {
    "name": "Lillet",
    "category": "Aperitif",
    "logo": "/images/pernod/57-logo_lillet_blue_240.png",
    "hero": null
  },
  {
    "name": "Long John",
    "category": "Scotch Whisky",
    "logo": "/images/pernod/91-brand-long-john-logo-240px.png",
    "hero": null
  },
  {
    "name": "Lot No. 40",
    "category": "World Whiskies",
    "logo": "/images/pernod/58-brand-lotno-40-logo-240px.png",
    "hero": null
  },
  {
    "name": "Malibu",
    "category": "Liqueur & Bitters",
    "logo": "/images/pernod/41-malibu_logo_240.png",
    "hero": null
  },
  {
    "name": "Martell",
    "category": "Cognac & Brandy",
    "logo": "/images/pernod/43-martell_logo_240.png",
    "hero": "/images/pernod/21-maison_martell_interior_2880x1234.jpg"
  },
  {
    "name": "Method and Madness",
    "category": "Irish Whiskey",
    "logo": "/images/pernod/60-brand-method-and-madness-logo-240px.png",
    "hero": null
  },
  {
    "name": "Midleton Very Rare",
    "category": "Irish Whiskey",
    "logo": "/images/pernod/61-brand-midleton-very-rare-logo-240px.png",
    "hero": "/images/pernod/31-midleton_distillery.jpg"
  },
  {
    "name": "Monkey 47",
    "category": "Gin",
    "logo": "/images/pernod/70-brand-monkey-47-logo-240px.png",
    "hero": null
  },
  {
    "name": "Mumm",
    "category": "Champagne",
    "logo": "/images/pernod/44-brand-mumm-logo-240px.png",
    "hero": "/images/pernod/34-mumm_moulin_verzenay.jpg"
  },
  {
    "name": "Ojo de Tigre",
    "category": "Tequila & Mezcal",
    "logo": "/images/pernod/42-ojo-de-tigre-logo_bleu.png",
    "hero": null
  },
  {
    "name": "Olmeca",
    "category": "Tequila & Mezcal",
    "logo": "/images/pernod/92-brand-olmeca-logo-240px.png",
    "hero": null
  },
  {
    "name": "Ostoya",
    "category": "Vodka",
    "logo": "/images/pernod/73-ostoya-logo_240.png",
    "hero": null
  },
  {
    "name": "Passport Scotch",
    "category": "Scotch Whisky",
    "logo": "/images/pernod/93-brand-passport-scotch-logo-240px.png",
    "hero": null
  },
  {
    "name": "Pastis 51",
    "category": "Aperitif",
    "logo": "/images/pernod/94-pastis_51_logo_240.png",
    "hero": null
  },
  {
    "name": "Pernod",
    "category": "Aperitif",
    "logo": "/images/pernod/74-brand-pernod-logo-240px.png",
    "hero": null
  },
  {
    "name": "Perrier-Jouët",
    "category": "Champagne",
    "logo": "/images/pernod/45-brand-perrier-jouet-logo-240px.png",
    "hero": "/images/pernod/32-maison_belle_epoque.jpg"
  },
  {
    "name": "Plymouth Gin",
    "category": "Gin",
    "logo": "/images/pernod/75-brand-plymouth-gin-logo-240px.png",
    "hero": null
  },
  {
    "name": "Powers",
    "category": "Irish Whiskey",
    "logo": "/images/pernod/76-brand-powers-logo-240px.png",
    "hero": null
  },
  {
    "name": "Rabbit Hole",
    "category": "World Whiskies",
    "logo": "/images/pernod/77-brand-rabbit-hole-logo-240px.png",
    "hero": null
  },
  {
    "name": "Ramazzotti",
    "category": "Liqueur & Bitters",
    "logo": "/images/pernod/95-logo-ramazzotti_240.png",
    "hero": null
  },
  {
    "name": "Redbreast",
    "category": "Irish Whiskey",
    "logo": "/images/pernod/78-brand-redbreast-logo-240px.png",
    "hero": null
  },
  {
    "name": "Ricard",
    "category": "Aperitif",
    "logo": "/images/pernod/46-brand-ricard-logo-240px.png",
    "hero": null
  },
  {
    "name": "Royal Salute",
    "category": "Scotch Whisky",
    "logo": "/images/pernod/47-brand-royal-salute-logo-240px.png",
    "hero": null
  },
  {
    "name": "Royal Stag",
    "category": "World Whiskies",
    "logo": "/images/pernod/96-royal-stag-logo-240.png",
    "hero": null
  },
  {
    "name": "Scapa",
    "category": "Scotch Whisky",
    "logo": "/images/pernod/79-brand-scapa-logo-240px_0.png",
    "hero": null
  },
  {
    "name": "Seagram's Gin",
    "category": "Gin",
    "logo": "/images/pernod/97-brand-seagrams-gin-logo-240px.png",
    "hero": null
  },
  {
    "name": "Secret Speyside",
    "category": "Scotch Whisky",
    "logo": "/images/pernod/71-brand-secret-speyside-logo-240px.png",
    "hero": null
  },
  {
    "name": "Smooth Ambler",
    "category": "World Whiskies",
    "logo": "/images/pernod/80-brand-smooth-ambler-logo-240px.png",
    "hero": null
  },
  {
    "name": "Something Special",
    "category": "Scotch Whisky",
    "logo": "/images/pernod/98-brand-something-special-logo-240px.png",
    "hero": null
  },
  {
    "name": "Spot Whiskeys",
    "category": "Irish Whiskey",
    "logo": "/images/pernod/54-spot_whiskeys.png",
    "hero": null
  },
  {
    "name": "Suze",
    "category": "Aperitif",
    "logo": "/images/pernod/81-brand-suze-logo-240px.png",
    "hero": null
  },
  {
    "name": "The Deacon",
    "category": "Scotch Whisky",
    "logo": "/images/pernod/72-the_deacon.png",
    "hero": null
  },
  {
    "name": "The Glenlivet",
    "category": "Scotch Whisky",
    "logo": "/images/pernod/48-the-glenlivet_logo_240.png",
    "hero": "/images/pernod/33-the_glenlivet_distillery.jpg"
  },
  {
    "name": "TX Whiskey",
    "category": "World Whiskies",
    "logo": "/images/pernod/83-brand-tx-logo-240px_0.png",
    "hero": null
  },
  {
    "name": "Ungava",
    "category": "Gin",
    "logo": "/images/pernod/84-brand-ungava-logo-240px.png",
    "hero": null
  }
];

export const FEATURED = PORTFOLIO.filter((b) => b.hero);
